In [1]:
import numpy
import pandas
import tensorflow.compat.v1
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [2]:
data = pandas.read_csv("https://raw.githubusercontent.com/matheuspolillo/K-Network/master/data/iris.csv")

data_to_view = [
    [data.loc[0, 'sepal_length'], data.loc[0, 'sepal_width'], data.loc[0, 'petal_length'], data.loc[0, 'petal_width'], data.loc[0, 'species']],
    [data.loc[50, 'sepal_length'], data.loc[50, 'sepal_width'], data.loc[50, 'petal_length'], data.loc[50, 'petal_width'], data.loc[50, 'species']],
    [data.loc[100, 'sepal_length'], data.loc[100, 'sepal_width'], data.loc[100, 'petal_length'], data.loc[100, 'petal_width'], data.loc[100, 'species']]
]
data_to_view = pandas.DataFrame(data_to_view, columns=['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species'])
data_to_view

sepal_length  sepal_width  petal_length  petal_width     species
0           5.1          3.5           1.4          0.2      setosa
1           7.0          3.2           4.7          1.4  versicolor
2           6.3          3.3           6.0          2.5   virginica

In [3]:
data.columns = ['Sepal_Length', 'Sepal_Width', 'Petal_Length', 'Petal_Width', 'Target']
data['Target'] = LabelEncoder().fit_transform(data['Target'].values)

data_to_view = [
    [data.loc[0, 'Sepal_Length'], data.loc[0, 'Sepal_Width'], data.loc[0, 'Petal_Length'], data.loc[0, 'Petal_Width'], data.loc[0, 'Target']],
    [data.loc[50, 'Sepal_Length'], data.loc[50, 'Sepal_Width'], data.loc[50, 'Petal_Length'], data.loc[50, 'Petal_Width'], data.loc[50, 'Target']],
    [data.loc[100, 'Sepal_Length'], data.loc[100, 'Sepal_Width'], data.loc[100, 'Petal_Length'], data.loc[100, 'Petal_Width'], data.loc[100, 'Target']]
]
data_to_view = pandas.DataFrame(data_to_view, columns=['Sepal_Length', 'Sepal_Width', 'Petal_Length', 'Petal_Width', 'Target'])
data_to_view

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width  Target
0           5.1          3.5           1.4          0.2       0
1           7.0          3.2           4.7          1.4       1
2           6.3          3.3           6.0          2.5       2

In [22]:
target_categorical = np_utils.to_categorical(data['Target'].values)
train, test = train_test_split(data, test_size=0.2, random_state=0)
print(
    '\n' + 'Valores categóricos' + '\n--------------------\n' + str(target_categorical[0]) + ' => Setosa\n' + str(target_categorical[50]) +
    ' => Versicolor\n' + str(target_categorical[100]) + ' => Virginica\n\n'
)

data_to_view = [
    [data.loc[0, 'Sepal_Length'], data.loc[0, 'Sepal_Width'], data.loc[0, 'Petal_Length'], data.loc[0, 'Petal_Width'], '1 0 0'],
    [data.loc[50, 'Sepal_Length'], data.loc[50, 'Sepal_Width'], data.loc[50, 'Petal_Length'], data.loc[50, 'Petal_Width'], '0 1 0'],
    [data.loc[100, 'Sepal_Length'], data.loc[100, 'Sepal_Width'], data.loc[100, 'Petal_Length'], data.loc[100, 'Petal_Width'], '0 0 1']
]
data_to_view = pandas.DataFrame(data_to_view, columns=['Sepal_Length', 'Sepal_Width', 'Petal_Length', 'Petal_Width', 'Target'])
data_to_view

Valores categóricos
--------------------
[1. 0. 0.] => Setosa
[0. 1. 0.] => Versicolor
[0. 0. 1.] => Virginica




Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Target
0           5.1          3.5           1.4          0.2  1 0 0
1           7.0          3.2           4.7          1.4  0 1 0
2           6.3          3.3           6.0          2.5  0 0 1

In [0]:
y_train = np_utils.to_categorical(train['Target'].values)
y_test = np_utils.to_categorical(test['Target'].values)

In [34]:
model = Sequential()
model.add(Dense(8, input_dim=4, activation='sigmoid'))
model.add(Dense(3, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

model.fit(train.loc[:, ['Sepal_Length', 'Sepal_Width', 'Petal_Length', 'Petal_Width']], y_train, epochs=100, batch_size=1, verbose=0)

In [33]:
loss, acc = model.evaluate(test.loc[:, ['Sepal_Length', 'Sepal_Width', 'Petal_Length', 'Petal_Width']], y_test, verbose=0)

print('Loss:', loss, '\nSuccess/Accuracy:', acc)

Loss: 0.08901248872280121 
Success/Accuracy: 1.0
